Update parameter definition for list_participants function in RemoteControl API
LimeSurvey/LimeSurvey pull request #1156
Opened 2018-10-24 05:57 UTC by raulangas

add <struct> type to  parameter definition for list_participants function in RemoteControl API so the function take the parameters and use it like filter of data

Fixed issue # : 
New feature # :
Changed feature # :
Dev: 
Dev:

2020-10-15 13:11 UTC, olleharstedt requested changes

2020-10-15 13:11 UTC, olleharstedt commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +     * @param array|struct $aConditions Optional conditions to limit the list, e.g. with array('email' => 'info@example.com')
Why is this needed? Is struct a PHPDoc standard type?

2020-10-15 13:24 UTC, cdorin93 commented
The issue is already fixed in current master. Thank you all for your contributions! I will now close the PR.

2021-03-26 19:53 UTC, closed without merging

2021-03-26 19:54 UTC, c-schmitz commented
Closed due to missing feedback.