Dev: less potential issue with console
LimeSurvey/LimeSurvey pull request #1426
Opened 2020-05-22 17:09 UTC by Shnoulle

Dev: config-default rootdir to realpath(dirname(dirname(dirname(__FILE__))))
Dev: with set a good rootdir, all other are better set
Dev: allow usage of configdir : i NEVER use this settings

2020-05-31 14:26 UTC, tammoterhark commented on application/config/config-defaults.php
> +* Usage of dirname like intenal.php
intenal or internal?

2021-02-25 18:02 UTC, olleharstedt requested changes
Needs to pull and resolve conflicts again, it seems.

2021-03-29 11:14 UTC, c-schmitz commented
@Shnoulle You still want to merge this?

2021-03-29 11:53 UTC, Shnoulle commented
Yes, but need fix (and test)

I set to draft , near one year old request

2022-02-25 08:49 UTC, c-schmitz commented
Same here: Either we finish this or we close it.

2022-02-28 17:26 UTC, Shnoulle commented
I close , i do another pull request

2022-02-28 17:26 UTC, closed without merging