New feature #16832: Add user group functions to LimeSurveyAPI
LimeSurvey/LimeSurvey pull request #1663
Opened 2020-11-20 19:18 UTC by flowdnb

New feature #16832: Add user group functions to LimeSurveyAPI

Dev: Allow plugins to read and create user group, add/remove user from group

2021-01-21 10:35 UTC, olleharstedt requested changes

2021-01-21 10:35 UTC, olleharstedt commented on application/libraries/PluginManager/LimesurveyApi.php
> +    public function userInGroupAction($ugid, $uid, $action)
Please remove `$action` and split the function in two parts, one for remove, one for add. If the functions have code in common, split it into a third private function.

2021-01-21 10:45 UTC, Shnoulle commented
Not about this function but a general remark : if we add function again on API we have a really great file finally  … maybe find another way to set "this part was in API" ?

2021-01-21 10:46 UTC, Shnoulle commented on application/libraries/PluginManager/LimesurveyApi.php
> +            return false;
Throw Exception ?

2021-01-21 10:46 UTC, Shnoulle commented on application/libraries/PluginManager/LimesurveyApi.php
> +            if ($uid > 0 && \User::model()->findByPk($uid)) {
Same : throw Exception , no ?

2021-01-21 10:47 UTC, Shnoulle commented on application/libraries/PluginManager/LimesurveyApi.php
> +            if (strlen($db_group_name) > 21) {
No … must try to save or validate and return model->errors…

2021-01-21 10:48 UTC, Shnoulle commented on application/libraries/PluginManager/LimesurveyApi.php
> +            } elseif (\UserGroup::model()->find("name=:groupName", array(':groupName'=>$db_group_name))) {
Same : try to validate : return model->errors

2021-01-25 14:03 UTC, merged

2021-01-25 14:04 UTC, olleharstedt commented
Merged, but please consider also returning model errors if save fails.

2021-04-08 19:59 UTC, maziminke commented
@olleharstedt can we also backport this to LS 3.x API? That version is the LTS version which most customers use so it makes sense making it available there as well.
It is just a new API function, that should not cause any harm...

2021-04-09 07:11 UTC, olleharstedt commented
I can try to cherry-pick this into LS3 today. Shouldn't be a problem, as you say.

2021-04-10 15:12 UTC, olleharstedt commented
Welp, forgot. Please remind me next week.

2021-04-12 14:35 UTC, olleharstedt commented
Cherry-picked to LS3.

Reasons we approved internally:

* Zero or very low risk
* LS4 has been unstable long time
* Request by long-time partner