Fixed issue #15904: Default survey admin & admin email not copied from user profile
LimeSurvey/LimeSurvey pull request #1786
Opened 2021-02-25 15:11 UTC by gabrieljenik

Allow user to select who is the admin of the newly created survey.
Had to adapt the CreateSurvey services and related to be able to take survey_admin as a parameter

2021-02-25 17:17 UTC, olleharstedt requested changes

2021-02-25 17:17 UTC, olleharstedt commented on application/datavalueobjects/SimpleSurveyValues.php
> +    private $admin = 'inherit';
There's no need to make this private if you have both a (trivial) getter and setter, I think.

2021-02-25 17:17 UTC, olleharstedt commented on application/datavalueobjects/SimpleSurveyValues.php
> +    private $adminEmail = 'inherit';
Same here

2021-03-09 14:37 UTC, gabrieljenik reviewed
Updated code

2021-03-10 15:13 UTC, olleharstedt commented
Thanks!

Now go prepare your arguments for why getters/setters are always a good idea, even when trivial. :D

2021-03-10 15:16 UTC, gabrieljenik commented
> Now go prepare your arguments for why getters/setters are always a good idea, even when trivial. :D

I know which battles to avoud! haha

2021-03-10 15:44 UTC, gabrieljenik commented
> │ Error: Call to undefined method LimeSurvey\Datavalueobjects\SimpleSurveyValues::setBaseLanguage()
> 
> │
> 
> │ /home/travis/build/LimeSurvey/LimeSurvey/tests/unit/models/CreateSurveyServiceTest.php:44

I knew I should have stood stronger on that battle!

2021-03-10 15:49 UTC, gabrieljenik commented
> │ Error: Call to undefined method LimeSurvey\Datavalueobjects\SimpleSurveyValues::setBaseLanguage()
> 
> │
> 
> │ /home/travis/build/LimeSurvey/LimeSurvey/tests/unit/models/CreateSurveyServiceTest.php:44

Let's see how travis reacts now

2021-03-11 17:03 UTC, merged