Fixed issue #16782: Survey groups : theme options: same theme name appear multiple time in list
LimeSurvey/LimeSurvey pull request #1823
Opened 2021-03-26 21:13 UTC by gabrieljenik

Fixing issue and deleting wrongly generated records: duplicate template configurations. Keeping the first one.

2021-03-27 10:29 UTC, Shnoulle commented
Original issue was fixed ? No way to get multiple one ?

2021-03-29 14:02 UTC, gabrieljenik commented
> Original issue was fixed ? No way to get multiple one ?

We think issue is solved and duplicates shouldn't be created (in relation to this issue/situation).
Why...? Have found a crack?

2021-04-08 10:13 UTC, c-schmitz requested changes

2021-04-08 10:13 UTC, c-schmitz commented on application/helpers/update/updatedb_helper.php
> +            $oDB->createCommand()->update('{{settings_global}}', array('stg_value' => 442), "stg_name='DBVersion'");
Wrong DBVersion here

2021-04-08 13:24 UTC, gabrieljenik commented on application/helpers/update/updatedb_helper.php
> +            $oDB->createCommand()->update('{{settings_global}}', array('stg_value' => 442), "stg_name='DBVersion'");
Fixed. Thanks!

2021-04-09 07:33 UTC, merged