[ENH] Add RPC function to delete a response using its ID
LimeSurvey/LimeSurvey pull request #1926
Opened 2021-06-16 13:40 UTC by arnaudbore

Add RPC function to delete a response depending on the ID of the response. @olleharstedt 
This PR followed this original one #78

2021-06-16 13:49 UTC, Shnoulle requested changes
No code only in remote control : remote control must do exactly the same than GUI : not more, not less.

2021-06-16 13:49 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                    // delete the files
Better to use `Response::model($iSurveyID)->findByPk($iResponseID);` delete file is included 
https://github.com/LimeSurvey/LimeSurvey/blob/f5cbc5748fb8d759ab8fff2fa3b50cc5f3dc6ed9/application/models/Response.php#L10

Then : no need to copy code here.

2021-06-16 13:49 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                        Survey_timings::model($iSurveyID)->deleteByPk($iResponseID);
Must add in Reponse model too then. 
https://github.com/LimeSurvey/LimeSurvey/blob/f5cbc5748fb8d759ab8fff2fa3b50cc5f3dc6ed9/application/models/Response.php#L10

2021-06-16 13:50 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                    // delete the files
PS : maybe `SurveyDynamic::model($iSurveyID)->findByPk($iResponseID)->delete();` must call `Response::model($iSurveyID)->findByPk($iResponseID)->delete();` ;)

2021-06-16 16:14 UTC, olleharstedt commented
Thanks for the review, Denis!!

2021-06-16 16:24 UTC, Shnoulle requested changes
Still some issue, and i think tou can no t use `Survey_dynamic` ? You test if it work ?

2021-06-16 16:25 UTC, Shnoulle commented
> Thanks for the review, Denis!!

OK with you too ? Delete timing in response is great for GUI too (needed but no bug report)

2021-06-16 16:28 UTC, Shnoulle requested changes

2021-06-16 16:28 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                    $oResult.deleteFiles();
`$oResult->deleteFiles();` but not needed

2021-06-16 16:28 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                    $oResult.deleteTimings();
`$oResult->deleteTimings();` but not needed

2021-06-16 16:28 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                $oResult = Response::model($iSurveyID)->findByPk($iResponseID);
No clean rules but `$Response = Response::model($iSurveyID)->findByPk($iResponseID);` seems clearer

https://manual.limesurvey.org/Coding_guidelines#Naming_convention

2021-06-16 17:02 UTC, Shnoulle reviewed
Seems cool

2021-06-16 17:04 UTC, Shnoulle approved these changes
Seems Ok, maybe update the return value ? And need to test

2021-06-16 17:04 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                    return array('iSurveyID'=>$iSurveyID);
See 
https://github.com/LimeSurvey/LimeSurvey/blob/f5cbc5748fb8d759ab8fff2fa3b50cc5f3dc6ed9/application/helpers/remotecontrol/remotecontrol_handle.php#L1939 

Maybe `return array($iResponseID=>'deleted');`

2021-06-17 05:55 UTC, Shnoulle commented
@arnaudbore i say maybe  : need discussion ;) . You think same ?

2021-06-17 10:11 UTC, arnaudbore commented
Sorry, I really thought it was a good idea and decided to move forward.

2021-06-17 12:40 UTC, olleharstedt commented
Now all we need is a written test...

2021-06-17 13:03 UTC, arnaudbore commented
I don't find any place in the repo where others tests are done. If you tell me where it is I can write the test.

2021-06-17 13:05 UTC, olleharstedt commented
Have a look in this folder: https://github.com/LimeSurvey/LimeSurvey/tree/master/tests/unit/helpers/remotecontrol

I think you could copy-paste a lot. Ask if you have any questions.

2021-06-17 13:10 UTC, arnaudbore commented
It's in the master not in the 3.x branch.

2021-06-17 13:30 UTC, olleharstedt commented
We prefer not to put new features into an old LTS version. Is it OK if we include it in LS 5.1.0 instead?

2021-06-17 14:24 UTC, arnaudbore commented
I don't think it will break anything since it's very specific and controlled. The admin won't upgrade to 5.1.0 :( 
We can test it on 5.1.0 and "easily" admit it will have the same behaviour on 3.x. I think this kind of use is very niche. What do you think ?

2021-06-17 14:26 UTC, olleharstedt commented
Yep, it's true that the risk is low when adding new API calls, but it should go into 5.1 dev branch first and then be cherry-picked into LTS after.

2021-06-17 14:28 UTC, arnaudbore commented
Ok I'll check if a rebase to 5.1 is painless and then add a test.

2021-06-17 14:36 UTC, olleharstedt commented
Thanks!!

2021-06-17 14:37 UTC, olleharstedt commented
The major difference between LTS and LS4/LS5 is how translations are handled in the database.

2021-06-17 14:53 UTC, arnaudbore commented
Which branch/tag should I use ? master ? development ? @olleharstedt

2021-06-17 14:57 UTC, olleharstedt commented
Moved to develop branch, but lots of conflicts. Hm. Doesn't make sense. Maybe open a new PR to develop branch directly?

2021-06-17 15:18 UTC, arnaudbore commented
Done see #1928

2021-06-17 15:36 UTC, closed without merging