Fixed issue #17223: With mandatory attribute : lost all current value when create a token
LimeSurvey/LimeSurvey pull request #1942
Opened 2021-07-01 19:15 UTC by gabrieljenik

Adding JS validation for required token attributes

2021-07-02 09:04 UTC, Shnoulle commented on assets/scripts/admin/tokens.js
> +            msg = "Please fill out this field";
? Why ? Browser have own language string here.

2021-07-02 09:05 UTC, Shnoulle commented
My opinion : better to use required attribute and when try to submit : go the 1st tab with error.

2021-07-05 16:24 UTC, gabrieljenik commented on assets/scripts/admin/tokens.js
> +            msg = "Please fill out this field";
Updated

2021-07-05 16:32 UTC, gabrieljenik commented
Now validation and the way of showing the validation mssage has been simplified using a toast message. 

HTML5 standard validation message  or field highlighting is not used anymore as to simplify the code (could be error prone and complex to do that on hidden tabs)

This is a starter. If we want to make it more complex or enhance it, it can be done from here.

The validation has also been added for the edit process, which didn't perform any validation at all

2021-07-22 09:17 UTC, olleharstedt commented
Please pull latest upstream to fix Github Actions.

2021-07-22 11:54 UTC, gabrieljenik commented
Ready!

2021-07-27 08:59 UTC, olleharstedt requested changes

2021-07-27 08:59 UTC, olleharstedt commented on assets/scripts/admin/tokens.js
> +    $valid = true;
Hm, why is `$valid` with a dollar sign here? It's JS, not PHP. :)

2021-07-27 08:59 UTC, olleharstedt commented on assets/scripts/admin/tokens.js
> +    $valid = true;
Guess you want to use "let" or "var" as well.

2021-08-11 13:06 UTC, merged