Dev #T1062: When user clicks the reset button the screen freezes while should reset to new default
LimeSurvey/LimeSurvey pull request #1993
Opened 2021-08-05 17:16 UTC by gabrieljenik

Added "reset" buttons for the specific screens on FullPagebar.

2021-11-09 12:47 UTC, Shnoulle commented on application/controllers/admin/SurveymenuController.php
> +                    'resetMenuEntries' => true, // TODO: Is this OK? It wasn't checking any permission on SurveymenuEntryController
Unsure ;  Permission::model()->hasGlobalPermission('superadmin', 'read'), ?

But tottaly unsure here … there are user menu entries ?

2021-11-09 12:49 UTC, Shnoulle reviewed
Code is OK

2021-11-09 12:49 UTC, Shnoulle commented on application/views/admin/super/fullpagebar_view.php
> +            <?php if (isset($fullpagebar['menus']['buttons']['resetMenus']) && $fullpagebar['menus']['buttons']['resetMenus']) :?>
I always prefer : `if (!empty($fullpagebar['menus']['buttons']['resetMenus'])`

shorter, and allow 0/""/null/false/not set for false

Like other dev want :)

2021-11-09 12:50 UTC, Shnoulle requested changes
Code OK, some remark not linked to code + conflict

2022-02-08 14:22 UTC, gabrieljenik commented
I think this can be closed.
Seems this has already been solved differently on master.
Zoho task is marked as done.

2022-02-08 14:22 UTC, closed without merging