Fix (17603): Removed language parameter from getQuestions method
LimeSurvey/LimeSurvey pull request #2040
Opened 2021-09-17 14:41 UTC by kpko

Removed language parameter from getQuestions method and query, as this column has been moved to another table (questionl10ns)

Fixed issue #17603

2021-09-17 14:53 UTC, Shnoulle commented
Yes, but before : getQuestions return the question object with language,

Maybe a solution to return the object with language part ? Help and Question ?

PS : i don't use any of this function ;)

2021-09-17 15:09 UTC, olleharstedt requested changes

2021-09-17 15:09 UTC, olleharstedt commented on application/libraries/PluginManager/LimesurveyApi.php
>          return \Question::model()->with('subquestions')->findAllByAttributes($conditions);
Keep language argument, but join with question_l10ns too

2021-09-21 08:59 UTC, kpko commented
Hi, I really don't know that much about the LimeSurvey code base. The suggested fix was the one we used as we only use single language surveys and LimeSurvey was crashing when calling getQuestions before. If there is a better fix, we should go for it.

Maybe it would be better to close this pull request and open up another issue about this to implement a better solution by one of the core contributors? 

Thanks so much for the good work. :)

2021-11-10 16:46 UTC, glimz commented
Hello, thank you for your contribution. However, since the PR does not conform to our code guidelines, we would close the issue and leave it open for another contributor to pick it up.

2021-11-10 16:46 UTC, closed without merging