Fixed issue #17654: spurious error "Incorrect username and/or password!" on auth_webserver autocreating user
LimeSurvey/LimeSurvey pull request #2087
Opened 2021-10-07 12:36 UTC by prigaux

it fixes spurious error "Incorrect username and/or password!" on auth_webserver autocreating user

details:

When autocreating a user, Authwebserver::newUserSession:
- calls Permission::setPermissions which dispatch a new event
  => which modify $this->event
- calls $this->setAuthSuccess ... which modifies "beforeHasPermission" event instead of modifying "newUserSession" event
LSUserIdentity::authenticate which dispatched "newUserSession" event checks $authEvent->get('result') which is still null and sets $result as error.

Fixed issue #<Mantis issue number>:
New feature #<Mantis issue number>:
Dev:

2021-11-10 16:20 UTC, glimz commented
Hello, is there a bug or feature report for this PR? If not, can you create one, so we can test and merge your PR?

2021-11-10 17:05 UTC, prigaux commented
The issue is https://bugs.limesurvey.org/view.php?id=17654

2021-11-26 15:19 UTC, glimz commented
Hello @prigaux , can you fix the merge conflict?

2021-11-26 15:50 UTC, prigaux commented
conflict resolved (i've rebased the commit and force pushed the new one)

2021-11-26 16:47 UTC, Shnoulle requested changes
I really think it's a risky way … and can break a lot of plugins

2021-11-26 16:47 UTC, Shnoulle commented on application/libraries/PluginManager/PluginManager.php
> +                    if ($prev_event) $subscription[0]->setEvent($prev_event);
> I agree my proposition may break things... /o\

Still think it's not the better way to fix this issue …

What happen when plugoin already [call event inside other event ](https://gitlab.com/SondagesPro/QuestionSettingsType/TextEditOnDemand/-/blob/master/TextEditOnDemand.php#L268)? 
No way to get multiple events ?
 What happen for plugin with own events ?
etc …

2021-11-27 07:49 UTC, Shnoulle commented
I take the issue and find another fix with less potential issue.

2021-11-27 08:06 UTC, Shnoulle commented
I check with a false plugin to see what happen exactly.

2021-11-27 09:09 UTC, Shnoulle commented
OK,

Seem better than i think https://github.com/Shnoulle/CheckIssue17654Fix/

@gabrieljenik , @maziminke : did you see other test  to do to check plugins compatibility ?

2021-11-27 09:12 UTC, Shnoulle requested changes
Need to be PSR12 compliant,

Else : wait more idea for checking

2021-11-27 09:12 UTC, Shnoulle commented on application/libraries/PluginManager/PluginManager.php
> +                    if ($prev_event) $subscription[0]->setEvent($prev_event);
Else PSR12 : https://manual.limesurvey.org/How_to_contribute_new_features#Code_sniffer

2021-11-27 15:23 UTC, gabrieljenik commented
I agree. I don't like a lot the original approach.
Feels like could break something core about events: They are used for retuning content/results from plugins.
I believe the best is to do a quick call to make sure we are on the same page about original problem and approach.

2021-11-28 00:19 UTC, Shnoulle commented
See my plugins : this is really better after this fix, but ?
Did i test all solution ? Some plugin can broke ?

Maybe we can test some of our complex plugins ? For example pdfreport with LimMPDF ? And i have some plugins using some event created by another plugin …

2021-11-29 18:06 UTC, gabrieljenik commented
hmm not sure. The approach doesn't feel right.
It is not a matter of testing.

2021-11-30 07:29 UTC, Shnoulle commented
> hmm not sure. The approach doesn't feel right.

Same for me, but clearly : be inside `beforeQuestionRender` function subscribed for `beforeQuestionRender` but return `beforeHasPermission` event seems an issue.

Maybe move this to develop and fix [AuthPluginBase](https://github.com/LimeSurvey/LimeSurvey/blob/80b1d47a0f05102ee6eecdb115826ab8af4e0e9d/application/libraries/PluginManager/AuthPluginBase.php#L90) to alow send current event in setAuthSuccess and setAuthFailure ? And send the saved event in webauth .

2021-11-30 12:36 UTC, gabrieljenik commented
> Same for me, but clearly : be inside beforeQuestionRender function subscribed for beforeQuestionRender but return beforeHasPermission event seems an issue.

Yes, there is a bug. Agree

> Maybe move this to develop and fix AuthPluginBase to alow send current event in setAuthSuccess and setAuthFailure ? And send the saved event in webauth .

Not sure. I need to get deeper in the bug. But definitily would treat it in a new PR.

2022-05-10 14:30 UTC, gabrieljenik commented
I believe this can be closed as this is followed up on #2170, right?
If not, please reopen.

Thanks!

2022-05-10 14:30 UTC, closed without merging