Fixed issue #17500: When mass-deleting, list survey names and ids to be deleted
LimeSurvey/LimeSurvey pull request #2100
Opened 2021-10-18 12:46 UTC by gabrieljenik

2021-11-03 11:20 UTC, Shnoulle requested changes
1. json decode as array,
2. Must check if it's a valid array
3. Must check if it's valid surveyid

2021-11-03 11:20 UTC, Shnoulle commented on application/controllers/admin/surveyadmin.php
> +        $aSurveys = json_decode(Yii::app()->request->getPost('$oCheckedItems'));
`json_decode(Yii::app()->request->getPost('$oCheckedItems'), true);`

Must return an array.

2021-11-05 17:55 UTC, gabrieljenik commented on application/controllers/admin/surveyadmin.php
> +        $aSurveys = json_decode(Yii::app()->request->getPost('$oCheckedItems'));
Although I hardly believe there could be an error arising from that line, I understand your point.
Still, if we return an error, the ajax is not prepared to handle it (happens with most of the ajax).

Let me see what we can think ok...

2021-11-07 10:19 UTC, Shnoulle requested changes
$results != $aResults ,

Seems you set and return `$results` but update `$aResults`

Can you check please ?

2021-11-07 10:19 UTC, Shnoulle commented on application/controllers/admin/surveyadmin.php
> +        $results = [];
`$results `

2021-11-07 10:19 UTC, Shnoulle commented on application/controllers/admin/surveyadmin.php
> +                $aResults[$surveyId]['title']  = $survey->correct_relation_defaultlanguage->surveyls_title;
`$aResults`

2021-11-07 10:19 UTC, Shnoulle commented on application/controllers/admin/surveyadmin.php
> +                'aResults'     => $results,
`$results `

2021-11-07 10:20 UTC, Shnoulle commented on application/controllers/admin/surveyadmin.php
> +        $aSurveys = json_decode(Yii::app()->request->getPost('$oCheckedItems'));
Using POST value : always have potential issue by user value. All user value must be checked :)

2021-11-09 12:56 UTC, Shnoulle requested changes
Set `$results `
Update `$aResults`
use ` $results`

2021-11-09 14:46 UTC, Shnoulle approved these changes

2021-11-10 14:34 UTC, merged