Fixed issue #16230: Reload survey (token answer persistence) don't really reload
LimeSurvey/LimeSurvey pull request #2211
Opened 2022-01-14 18:29 UTC by Shnoulle

Dev: LEMtokenResume with reload by token too
Dev: set maxstep to totalstep if needed
Dev: Create LimeExpressionManager::SetRelevanceTo to set relevance before JumpTo in case of reload
Dev: When reload : initFirstStep function before all other: then move reloading part here.

2022-01-14 18:33 UTC, Shnoulle commented
@glimz In project management it set as done : https://github.com/LimeSurvey/LimeSurvey/pull/2211

2022-02-07 13:28 UTC, gabrieljenik requested changes
Some changes were requested throught the code.

2022-02-08 08:28 UTC, Shnoulle commented on application/helpers/expressions/em_manager_helper.php
> +                    // TODOACTUEL
Set it before :)

In fact ;: i want to create a new settings (global or not unsure) for "DefaultQuestionRelevanceStatus)

but it's another question here.

2022-02-08 13:36 UTC, gabrieljenik approved these changes
Code OK.
Not tested.

2022-02-08 13:45 UTC, Shnoulle commented
Maybe need test ?

2022-02-10 11:59 UTC, merged