Fixed issue #17873: Remote Control `delete_language` fails to remove language
LimeSurvey/LimeSurvey pull request #2235
Opened 2022-02-08 04:30 UTC by edgarrmondragon

Fixed issue #17873:  Remote Control `delete_language` fails to remove language

2022-02-08 15:16 UTC, olleharstedt requested changes

2022-02-08 15:16 UTC, olleharstedt commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                $iLanguageKey = array_search($sLanguage, $aLanguages, true)
Missing semi-colon on this line

2022-02-09 02:08 UTC, edgarrmondragon commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +                $iLanguageKey = array_search($sLanguage, $aLanguages, true)
🤦 thanks @olleharstedt! I fixed it.

2022-02-09 12:17 UTC, olleharstedt commented
@Shnoulle You want to review this change before merge?

2022-02-09 14:33 UTC, Shnoulle commented
? Seems OK, but not tested .

2022-02-10 01:33 UTC, edgarrmondragon commented
@Shnoulle I assumed this method was already being tested somewhere in [tests/unit/helpers](https://github.com/LimeSurvey/LimeSurvey/tree/master/tests/unit/helpers) but you're right there are none. I might be able to add a test but probably not until the weekend.

2022-02-10 07:10 UTC, Shnoulle commented
@edgarrmondragon : i just mean i didn't test it manually ;)

2022-02-10 07:39 UTC, c-schmitz commented
@edgarrmondragon Adding a test would be great. We will wait with the merge until then. Thank you for your help!

2022-03-07 19:23 UTC, c-schmitz approved these changes

2022-03-07 19:26 UTC, merged