Fixed issue #17862: Invalid url in admin (usage of HTTP_HOST)
LimeSurvey/LimeSurvey pull request #2282
Opened 2022-03-03 17:01 UTC by gabrieljenik

Compiling of JS is pending

2022-03-03 17:16 UTC, Shnoulle commented
>  Strangely : «Add question» is OK but not «add group» 

?

2022-03-07 12:26 UTC, gabrieljenik commented
> > Strangely : «Add question» is OK but not «add group»
> 
> ?

Sorry, don't understand.
What do you mean?

2022-03-07 15:52 UTC, Shnoulle commented
report : Go to manage admin survey :

1. Can create survey, can edit global settings a lot os OK
2. Add button question in structure goes to limesurvey.intra
3. Global survey settings tab goes all to limesurvey.intra

In structure : Add question is broken , not add group (i made an error in my report)

**BUT** : i can not reproduce today … on my local nginx …

2022-03-07 18:38 UTC, c-schmitz approved these changes

2022-03-07 18:40 UTC, c-schmitz requested changes
Code is okay, but CI is not green

2022-03-08 10:02 UTC, olleharstedt commented
So it's finally happened. We need to apply a bug fix in adminsidepanel and the build system is FUBAR...

2022-03-08 10:05 UTC, olleharstedt commented
I think Jessica tried to update to Vue 3, but you probably have to downgrade it to Vue 2 again to easily apply a new fix.

2022-03-11 10:02 UTC, olleharstedt commented
Jessica is back next week, maybe we'll assign it to her then. Or it will have to be a team effort.

Also, death to dependabot.

2022-03-11 10:05 UTC, olleharstedt commented
I moved the task to our internal Zoho project, we'll try to solve it.

2022-03-15 12:15 UTC, naiteon commented
@gabrieljenik side menu has been fixed. If you find any problems reach out to me please.

2022-03-15 12:49 UTC, gabrieljenik commented
@naiteon Thanks! What was it?
What are the next steps then? Should we merge master in here and recompile?

2022-03-15 12:55 UTC, olleharstedt commented
Sorry, still broken. False alarm. :(

2022-03-18 13:04 UTC, gabrieljenik commented
@naiteon Thanks! What was it?
What are the next steps then? Should we merge master in here and recompile?

2022-03-18 15:56 UTC, naiteon commented
@gabrieljenik Hey Gabriel! I think you should stash your changes, rebase your branch against master, then apply the stashed changes and proceed with the PR.

2022-03-18 15:56 UTC, naiteon commented
@gabrieljenik oh no, there is no need for recompiling it because the distribution files are included in the repo.

2022-03-21 11:30 UTC, olleharstedt commented
> @gabrieljenik As for compiling the adminsidepanel, there is no need for recompiling it because the distribution files are included in the repo.

This fix changes the adminsidepanel src files, that's why they need to be recompiled.

2022-03-21 19:47 UTC, gabrieljenik commented
Ready for re review!

2022-04-25 10:14 UTC, Shnoulle approved these changes

2022-04-25 10:15 UTC, Shnoulle commented on assets/packages/adminsidepanel/src/components/subcomponents/_questionsgroups.vue
> +                return this.createQuestionLink + '&gid=' + LS.reparsedParameters().combined.gid;
Really specific i think …

2022-04-27 14:11 UTC, gabrieljenik commented
I think this can be merged. Seems tested and also reviewed? Please someone elese confirm it. Thanks

2022-04-28 08:08 UTC, merged