Fixed issue #17678: VV export didn't shown sub question
LimeSurvey/LimeSurvey pull request #2283
Opened 2022-03-03 18:41 UTC by Shnoulle

Dev: feature related to manage question text type and abbreviation

Fixed issue #<Mantis issue number>:
New feature #<Mantis issue number>:
Dev:

2022-03-03 18:42 UTC, Shnoulle commented
![Capture d’écran du 2022-03-03 19-41-56](https://user-images.githubusercontent.com/1439428/156631072-b9367023-8176-44b6-a3b8-1f6938dd522e.png)

2022-03-07 07:40 UTC, Shnoulle commented on application/views/admin/export/vv_view.php
> +                            <?php eT("Separator for question and subquestion"); ?>
Arg …

2022-03-07 18:36 UTC, c-schmitz requested changes

2022-03-07 18:36 UTC, c-schmitz commented on application/views/admin/export/vv_view.php
> +                            <p class="help-block"><?php eT("If you want to import survey on old installation or if your survey have problem: use old version (automatically selected if some code are d
Please correct to:
"If you want to import the response data in older version or if your survey has integrity problem, please use the old export version (automatically selected if there are duplicate codes)."

2022-03-07 18:36 UTC, c-schmitz commented on application/views/admin/export/vv_view.php
> +                                <option value="parenthesis" selected><?php eT("Sub question wrapped by parenthesis"); ?></option>
"Subquestion wrapped by parentheses"

2022-03-07 18:36 UTC, c-schmitz commented on application/views/admin/export/vv_view.php
> +                            <?php eT("Separator for question and subquestion:"); ?>
"Separator between question and subquestion:"

2022-03-07 18:36 UTC, c-schmitz commented on application/controllers/admin/Export.php
> +            fputcsv($vvOutput, $firstline, "\t");
Nice!

2022-05-10 10:24 UTC, merged