Fixed issue #17940: Array filter in combination with 'equals sum value' feature does not sum up values correctly
LimeSurvey/LimeSurvey pull request #2288
Opened 2022-03-10 19:33 UTC by gabrieljenik

2022-03-11 07:16 UTC, Shnoulle commented
You mean the `sumRemainingEqn` set to twig file is not always this one of this question ?

If yes : this must be fixed, in my opinion : allow QuestionTheme to get current value to so something is **needed** for other theme. A way to get the current attributes of the question.

Else must check all other question : just fo rmultiple text :+1: 

https://github.com/LimeSurvey/LimeSurvey/blob/1e04d703e926f5c9cf22335f9c7cb9f00b81b761/application/views/survey/questions/answer/multipleshorttext/rows/answer_row_inputtext.twig#L42
https://github.com/LimeSurvey/LimeSurvey/blob/1e04d703e926f5c9cf22335f9c7cb9f00b81b761/application/views/survey/questions/answer/multipleshorttext/rows/answer_row_inputtext.twig#L33
https://github.com/LimeSurvey/LimeSurvey/blob/1e04d703e926f5c9cf22335f9c7cb9f00b81b761/application/views/survey/questions/answer/multipleshorttext/rows/answer_row_inputtext.twig#L49

Maybe it's the way of using it ?

2022-03-11 09:31 UTC, Shnoulle commented
Need a better lss to make a better fix …
Because the original issue are not always reproducible ...

2022-03-11 13:26 UTC, gabrieljenik commented
> Need a better lss to make a better fix … Because the original issue are not always reproducible ...

This helps
[limesurvey_survey_144143_(1).lss.txt](https://github.com/LimeSurvey/LimeSurvey/files/8232206/limesurvey_survey_144143_.1.lss.txt)
?

2022-03-11 13:29 UTC, gabrieljenik commented
> If yes : this must be fixed, in my opinion : allow QuestionTheme to get current value to so something is needed for other theme. A way to get the current attributes of the question.

I agree. This problem could mess with other themes as well.

> Maybe it's the way of using it ?

What do you mean?
We need more time to research it.

> twig processString use processStepString : no question id inside.

Yes and that's a problem if you want to use EM as the code generated by the EM heavily relies on the question id to name the replacement variables.

2022-03-11 14:56 UTC, Shnoulle commented
> > Need a better lss to make a better fix … Because the original issue are not always reproducible ...
> 
> This helps [limesurvey_survey_144143_(1).lss.txt](https://github.com/LimeSurvey/LimeSurvey/files/8232206/limesurvey_survey_144143_.1.lss.txt) ?

Need condition on last question : ok, realy more clear :)


> Yes and that's a problem if you want to use EM as the code generated by the EM heavily relies on the question id to name the replacement variables.

If it's about order of question : what happen if you put 2 questions between the Multiple numeric : and no way to fix ?

We don't have another fix some week ago about order of question ?

2022-03-11 15:14 UTC, Shnoulle commented
This issue : https://bugs.limesurvey.org/view.php?id=13529 reappear …  «Group title and description + Survey name and description are not updated vi EM javascript something change in expression manager between 3.6 and current .

2022-03-11 15:46 UTC, Shnoulle commented
Some idea :

1. Update twig function to allow qid usage (and use it here)
2. Report again the issue about Group title and description are not updated via EM javascript (because it work at a time : processString and processStepString are created to fix THIS issue.
3. Check the other usage of processString

With 1 : you don't broke possible hacked theme  (Question or Survey) : there still the same issue, but data sent is the same.

2022-03-11 16:01 UTC, gabrieljenik commented
With 1. the issue is we need to send the QID to the twig, which is not sent always.
I would say to open a new ticket, and then we review approaches.

I like the idea of using a static variable for QID.
That would be set by the renderer.
Could be read inside twig, when needed.

2022-03-11 16:06 UTC, Shnoulle commented
> With 1. the issue is we need to send the QID to the twig, which is not sent always. I would say to open a new ticket, and then we review approaches.

Ah shit !

> I like the idea of using a static variable for QID. That would be set by the renderer. Could be read inside twig, when needed.


Related : https://bugs.limesurvey.org/view.php?id=14228 ?

2022-03-11 20:14 UTC, gabrieljenik commented
> sumRemainingEqnDynamic

What is this? Didn't found it in the code.

2022-03-12 11:47 UTC, Shnoulle commented
> > sumRemainingEqnDynamic
> 
> What is this? Didn't found it in the code.

Adding a new var to be used in twig : then : old twig work (except if there are an hidden question wait same condition at end of the group).

- sumRemainingEqn : not updated attribute
- sumRemainingEqnDynamic : updated attribute

2022-03-17 18:43 UTC, gabrieljenik commented
> or a quick fix without broke hacked them

On `sumRemainingEqn` we are sending an already processed string. If that gets reprocessed (say by a not-yet-updated custom theme), `sumRemainingEqn` will not get updated, as there is nothing to process there.

In which situation do you forsee the theme being broken?

2022-03-18 07:44 UTC, Shnoulle commented
Ah right :).

BUT : i really think QuestionTheme must receive always RAW value 

The issue in this bug are here : https://bugs.limesurvey.org/file_download.php?file_id=15712&type=bug
Not elsewhere.

2022-03-18 12:51 UTC, gabrieljenik commented
> i really think QuestionTheme must receive always RAW value

Why?

> The issue in this bug are here : https://bugs.limesurvey.org/file_download.php?file_id=15712&type=bug

You mean in version 3.25.20 ?

2022-03-18 13:54 UTC, Shnoulle commented
> > i really think QuestionTheme must receive always RAW value
> 
> Why?

To allow QuestionTheme or SurveyTheme maker to do exactly what they want. Maybe get is as static or get it as dynamic even if core use is as static

> > The issue in this bug are here : https://bugs.limesurvey.org/file_download.php?file_id=15712&type=bug
> 
> You mean in version 3.25.20 ?

I mean : issue [17940](https://bugs.limesurvey.org/view.php?id=17940) happen between  between 3.25.20 and 3.25.22

It's OK in 3.25.20 with the exact same twig code (usage of `processString`), but broke in 3.25.22.
The issue is somewhere here, a commit broke `processString` function.

2022-03-19 09:45 UTC, Shnoulle commented
> To allow QuestionTheme or SurveyTheme maker to do exactly what they want. Maybe get is as static or get it as dynamic even if core use is as static

Leave it for globally : https://bugs.limesurvey.org/view.php?id=14228

2022-03-19 09:46 UTC, Shnoulle requested changes
:+1:

2022-03-19 09:46 UTC, Shnoulle approved these changes

2022-03-21 07:30 UTC, merged