Fixed issue #18042: Path-relative stylesheet import (PRSSI) vulnerability
LimeSurvey/LimeSurvey pull request #2374
Opened 2022-04-26 21:07 UTC by gabrieljenik

2022-05-10 16:07 UTC, gabrieljenik commented
@c-schmitz Sorry. Got lost. Fix what? There are no issues I believe. Right?

2022-05-19 18:03 UTC, c-schmitz commented
> @c-schmitz Sorry. Got lost. Fix what? There are no issues I believe. Right?
Check out the pending issue above?

2022-05-19 18:04 UTC, c-schmitz requested changes

2022-05-19 18:05 UTC, c-schmitz commented on third_party/kcfinder/core/class/browser.php
> +        $schema = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https://' : 'http://';
Seems my change request was not visible because my review was still in status 'pending'. Now you should be able to see it.

2022-05-20 06:27 UTC, Shnoulle requested changes
Use Yii https://www.yiiframework.com/doc/api/1.1/CHttpRequest#getBaseUrl-detail

2022-05-20 06:27 UTC, Shnoulle commented on third_party/kcfinder/core/class/browser.php
> +        $schema = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') ? 'https://' : 'http://';
@gabrieljenik you can use https://www.yiiframework.com/doc/api/1.1/CHttpRequest#getBaseUrl-detail directly , no need to create a new function.
We extend Yii now (for session)

2022-05-20 13:36 UTC, Shnoulle approved these changes
:)
If it work , it's really a clean fix ;)

2022-06-30 18:07 UTC, Shnoulle approved these changes

2022-06-30 18:09 UTC, merged

2022-06-30 18:09 UTC, Shnoulle commented
Same for 3.X ?

2025-03-21 11:32 UTC, otheus commented
WTF guys? This patch completely breaks the kcfinder module. Did @Shnoulle actually test?  How does setting  html-base to YII's base-path from within vendor/kcfinder/browse.php actually fix anything?  All subsequent requests from browse.php (such as those loaded via tpl/tpl_*.php) will be from URI_BASE, not from URI_BASE/vendor/kcfinder . Finally, how would this fix anything security-related? All relative URIs invoked via base.php are already relative to vendor/kcfinder. 

I don't have access to see the original issue, so I cannot re-open it.

2025-03-21 11:34 UTC, Shnoulle commented
Merged on Jun 30, 2022 : yes, it was tested ....