Fixed issue #16907: Importing Question through Remote Control doesn't set new title for all languages
LimeSurvey/LimeSurvey pull request #2387
Opened 2022-05-02 19:13 UTC by gabrieljenik

There are several problems with importing questions.

1) The new "title" is only set in the first language (it is the problem of the ticket).
2) The new question text is also set to the first language only.
3) The new "title" is set after importing. In other words, if you want to import a question, whose title already exists, but set it at the moment (through the API call), you can't, because before setting the new one, the process will fail because of the duplication.

This particular ticket is simple, because the title has to always be the same. The text of the question is more complicated because setting the same text in all languages does not make sense. This ticket is only limited to item 1.

2022-05-06 08:31 UTC, Shnoulle commented
I completely rewrite all system on https://github.com/LimeSurvey/LimeSurvey/pull/2405

And adding potential issue with invalid title ( try to set title to `1234` for example : erreo happen but  nit shown)

2022-07-06 06:27 UTC, Shnoulle commented
We can not merge both : https://github.com/LimeSurvey/LimeSurvey/pull/2405/files#diff-22d09ac4b2de7e29721c3fc14eb239f215498a280b8c37f4b718074646f01f5dR1482

2022-07-06 06:28 UTC, Shnoulle requested changes
The https://github.com/LimeSurvey/LimeSurvey/pull/2405 fix it too and 2 other bug.

OK to close this one ?

2022-07-06 18:14 UTC, gabrieljenik commented
> The #2405 fix it too and 2 other bug.
> 
> OK to close this one ?

Sure, go ahead!

2022-11-15 12:24 UTC, closed without merging