Dev #18033: Model errors need friendlier messages
LimeSurvey/LimeSurvey pull request #2439
Opened 2022-05-24 13:19 UTC by gabrieljenik

Created a UserException class which can be friednly shown as a flash message or rendered as json message.
This is good for triggering exceptions directly from the model, for example, and ease its handling by the controller.

2022-05-24 14:12 UTC, Shnoulle reviewed
Why not https://www.yiiframework.com/doc/api/1.1/CHtml#errorSummary-detail usage ?

2022-05-24 14:12 UTC, Shnoulle commented on application/core/LSYii_Application.php
> +            $message .= "<br>" . implode("<br>", $errors);
🤔

2022-05-24 14:12 UTC, Shnoulle commented on application/core/LSYii_Application.php
> +            $outputData['message'] .= "<br>" . implode("<br>", $errors);
🤔

2022-05-25 15:56 UTC, Shnoulle requested changes
Usage of CHtml::errorSummary seems really the best

2022-06-09 14:12 UTC, gabrieljenik commented
ErrorSummary is just for models. We are doing something similar, but for more general usage.

Although it started for displaying erros from the model, could be used for errors within methods nested in a controller or a helper. Ex: MassiveActions.

2022-06-09 20:43 UTC, gabrieljenik commented
> I really think replace setDetailedErrorsFromModel($oQuestion); by CHtml::errorSummmary($oQuestion) is better.

`CHtml::errorSummmary` renders the errors.
I prefer to have someone else to render the errors.

> And really : the HTML produced here is … i have no word.

Not sure I understand. What do you mean?

When rendering the errors we are doing a basic formatting.
Of course could be better. Not sure it is worth it.

We could have used CHtml::errorSummmary, but now we have something more general which can be used for displaying more than model errors.

2022-06-10 06:28 UTC, Shnoulle commented
About html : 

- the attribute is already included in default Yii message , no need to add it again.
- it's a list of error … then produce an html list

And if you can add an header too …

Something like … [this](https://github.com/yiisoft/yii/blob/e1665bdc506cc8e054139f6dd91649e8e12feb5b/framework/web/helpers/CHtml.php#L2236)

2022-06-14 16:29 UTC, Shnoulle commented
Thanks you :).

Did you have a clean reproduce way ?

Enter 111 in a new question ?

2022-06-14 20:56 UTC, gabrieljenik commented
> Did you have a clean reproduce way ?
> 
> Enter 111 in a new question ?

The easiest is to put an invalid character in the question title and use save and close.

2022-06-15 07:29 UTC, Shnoulle commented
big difference between  develop and master before merging (Save and close part)
![questionCode-error-develop](https://user-images.githubusercontent.com/1439428/173768779-36f3f722-f69a-4ce5-b588-acb5ad3d88dd.gif)
![questionCode-error-master](https://user-images.githubusercontent.com/1439428/173768783-be5b2de6-ff3e-4fc1-8db2-8fa0f5ce7ef4.gif)

2022-06-15 07:37 UTC, Shnoulle commented
Like to have same clean HTML when save and close and save.

Not the wrapper (it's another issue) but the content
![Peek 15-06-2022 09-33](https://user-images.githubusercontent.com/1439428/173770293-993cbab7-549f-4ba4-b154-74105722f1cd.gif)

2022-06-15 07:38 UTC, Shnoulle requested changes
Same HTML (ul > li) with save and save and close.
If possible.

2022-06-15 07:38 UTC, Shnoulle commented on application/core/LSYii_Application.php
> +            $outputData['message'] .= "<br>" . implode("<br>", $errors);
Possible to use same HTML than https://github.com/LimeSurvey/LimeSurvey/pull/2439/files#diff-830594dcfebb3cf724c6c04a8b9791bf841a954d95a84614481007be4568a060R100 ?

2022-06-15 07:40 UTC, Shnoulle commented on application/core/LSYii_Application.php
> +            $outputData['message'] .= "<br>" . implode("<br>", $errors);
Oh … thing need JS improvment here …

2022-06-17 15:31 UTC, gabrieljenik commented
> big difference between develop and master before merging (Save and close part)

Big difference good?
We will do an update for rendering jsonExceptions and be back

2022-06-20 16:00 UTC, Shnoulle commented
> Big difference good?

develop throw a 500 error …

2022-06-21 14:47 UTC, Shnoulle commented
I create the issue about usage of Boostrap :)

2022-06-21 14:47 UTC, merged