Fixed issue #18209: Missing RemoteControl function to get the field mapping
LimeSurvey/LimeSurvey pull request #2479
Opened 2022-06-27 14:01 UTC by gabrieljenik

- Added get_fieldmap Remote Control function

2022-06-27 19:12 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
> +     * @param int $surveyId ID of the Survey
Optionnal param lang ?

2022-06-27 19:13 UTC, Shnoulle reviewed
See comments about language.

2022-06-28 12:45 UTC, Shnoulle approved these changes

2022-06-28 13:41 UTC, c-schmitz requested changes
Code looks fine, but please still add a test

2022-06-28 15:53 UTC, Shnoulle commented on tests/unit/helpers/RemoteControlTest.php
> +        $result = $handler->get_fieldmap($sessionKey, self::$surveyId, 'es');
:+1: multilingual test !

2022-06-30 07:41 UTC, c-schmitz approved these changes

2022-06-30 07:42 UTC, merged

2022-06-30 07:42 UTC, c-schmitz commented
Thanks. I also need this for 3.x