New feature #18375: Security Some plugin settings need encryption
LimeSurvey/LimeSurvey pull request #2645
Opened 2022-10-04 20:42 UTC by gabrieljenik

2022-10-05 07:16 UTC, Shnoulle commented
Yes, this fix the issue about API upgrade and password … 

I like to have a way to upgrade my plugin with existing password, i mean : with a plugin moving from version 1.2.4 to 1.3.0 with `New feature : encrypt password`

- Check current version (in DB) : if it's 1.2.4 : get the setting uncrypted
- Save it crypted 
- Update version number

I can do the same using a new setting ( current name : `smtppass` , new name : `smtpasscrypted`) delete previous one when goes to setting. 
Let me think for a few hours

2022-10-05 12:29 UTC, gabrieljenik commented
I think this discussion should be followed on this ticket: https://bugs.limesurvey.org/view.php?id=9056

2022-10-05 12:36 UTC, Shnoulle approved these changes

2022-10-05 12:38 UTC, Shnoulle commented
It work , previous value are not updated :)

2022-10-12 08:01 UTC, Shnoulle requested changes
The QuestionAttribute settings are not related to PluginSetting.

Must move to another file 

- https://manual.limesurvey.org/NewQuestionAttributes : get array, can append to array. Use QuestionAttribute model
- https://manual.limesurvey.org/NewSurveySettings : use (by default) PluginSetting model
- https://github.com/LimeSurvey/LimeSurvey/blob/e3efd7fb1771e39d18396315fa7b2be56b78e800/application/libraries/PluginManager/PluginBase.php#L257 use (by default) PluginSetting model

2022-10-12 12:53 UTC, Shnoulle commented on tests/data/plugins/NewQuestionAttributesPlugin.php
> +    protected $storage = 'DbStorage';
For me NewQuestionAttributesPlugin test QuestionAttributes and not something else .

We can use same plugin, but not in same file , no ?

2022-10-12 17:52 UTC, Shnoulle approved these changes
:+1: 

Maybe adding newSurveySettings event after.

2022-11-16 13:58 UTC, gabrieljenik commented
@c-schmitz @olleharstedt Not sure about the "need testing" tag here.
This is an automated test being added :)

2022-11-24 13:27 UTC, merged