Fixed issue #18415: Copy Survey: New Title shouldn't be mandatory
LimeSurvey/LimeSurvey pull request #2709
Opened 2022-11-08 18:48 UTC by gabrieljenik

2022-11-15 15:39 UTC, Shnoulle requested changes
I'm not for the test and set at same time here. Since there vare already a lot of if/elseif/elseif/else add a complication.

2022-11-15 15:39 UTC, Shnoulle commented on application/controllers/SurveyAdministrationController.php
> +                } elseif (!$sourceSurvey = Survey::model()->findByPk($iSurveyID)) {
Personally i'm for separate the set and the test.

2022-11-15 21:10 UTC, gabrieljenik commented
> I'm not for the test and set at same time here. Since there vare already a lot of if/elseif/elseif/else add a complication.

Yes, I know.
Not the best. But if not, I would had to do some code reorganization, and wanting to avoid it just for this small story.

2022-11-15 21:11 UTC, gabrieljenik commented on application/controllers/SurveyAdministrationController.php
> +                        $sNewSurveyName = $sourceSurvey->currentLanguageSettings->surveyls_title;
> $sourceSurvey = Survey::model()->findByPk($iSurveyID);
> $sNewSurveyName = $sourceSurvey->currentLanguageSettings->surveyls_title;

I didn't want to query the DB again. $sourceSurvey was already fetched couple of lines above when validating the survey id.

2022-11-16 07:32 UTC, Shnoulle commented on application/controllers/SurveyAdministrationController.php
> +                        $sNewSurveyName = $sourceSurvey->currentLanguageSettings->surveyls_title;
You are totally right, except for Survey :)

`Survey::model()->findByPk($iSurveyID)` use a static var 

https://github.com/LimeSurvey/LimeSurvey/blob/3215a764bf4033a490d70160b3f4eb2b3951b478/application/models/Survey.php#L981

It's not an issue (for Survey)

2022-11-16 07:36 UTC, Shnoulle commented
> > I'm not for the test and set at same time here. Since there vare already a lot of if/elseif/elseif/else add a complication.
> 
> Yes, I know. Not the best. But if not, I would had to do some code reorganization, and wanting to avoid it just for this small story.

Since select are required

```
$iSurveyID = sanitize_int(Yii::app()->request->getParam('copysurveylist'));
if (!$iSurveyID) {
    thrown 400 (bad request)
}
$sourceSurvey = Survey::model()->findByPk($iSurveyID);
if(empty($sourceSurvey)) {
//etc …
```

2022-11-16 13:08 UTC, gabrieljenik commented
Cosidering that the survey record is kind of  cached inside the model, I think that we can do a better fix without needing to do a whole code reorg.

2022-11-16 13:12 UTC, Shnoulle commented
> Cosidering that the survey record is kind of cached inside the model, I think that we can do a better fix without needing to do a whole code reorg.

See this another comment too https://github.com/LimeSurvey/LimeSurvey/pull/2709#issuecomment-1316514411

dropdown is mandatory (`required="required"`) then to get here witth an empty sid (or a string for sid) : user must hack HTML (or have a Man in the middle attack) : throw a 400 request in place of if/elseif :)

2022-11-16 13:15 UTC, gabrieljenik commented
> throw a 400 request in place of if/elseif :)

That's just one of the blocks in the chain of if/elseif.
I want to avoid code reorganization. If not bigger risk of unexpected errors.
Risk vs Benefit balance doesn't seem to good for me here

2022-11-16 14:07 UTC, Shnoulle commented
It's for $sourceSurvey = Survey::model()->findByPk($iSurveyID); :)

PS : since we already set to int : we can call `Survey::model()->findByPk(0);`  : it's OK in all DB
PS2:  `Survey::model()->findByPk('STRING');` break with an error 500 for PGsql

2022-12-06 21:03 UTC, gabrieljenik commented on application/controllers/SurveyAdministrationController.php
> +                        $sNewSurveyName = $sourceSurvey->currentLanguageSettings->surveyls_title;
Check now :)

2022-12-07 07:19 UTC, Shnoulle commented on application/views/surveyAdministration/tabCopy_view.php
> +                            <input type='text' id='copysurveyname' size='82' maxlength='200' name='copysurveyname' value='' class="form-control" />
> > Best : $sourceSurvey->currentLanguageSettings->surveyls_title
> 
> The source survey is selected from a dropdown on this screen.
> 

Arg, i'm a silly boy ;)

2022-12-07 07:20 UTC, Shnoulle requested changes
Just translation :)
Thank you.

2022-12-07 07:20 UTC, Shnoulle commented on application/views/surveyAdministration/tabCopy_view.php
> +                            <input type='text' id='copysurveyname' size='82' maxlength='200' name='copysurveyname' placeholder="Copy original survey title" value='' class="form-control" />
`eT("Copy original survey title")`

2022-12-12 13:23 UTC, gabrieljenik commented on application/views/surveyAdministration/tabCopy_view.php
> +                            <input type='text' id='copysurveyname' size='82' maxlength='200' name='copysurveyname' placeholder="Copy original survey title" value='' class="form-control" />
Updated!

2022-12-12 13:34 UTC, Shnoulle approved these changes

2022-12-15 13:17 UTC, merged