Fixed issue #18655: Data loss if field in response table it missing
LimeSurvey/LimeSurvey pull request #2946
Opened 2023-02-27 15:15 UTC by gabrieljenik

2023-02-27 16:04 UTC, Shnoulle reviewed
Unsure on Exception : i think we already have other : $ex->getMessage() ?

`sprintf($this->gT('The data could not be saved dur to %s'),$ex->getMessage())` maybe ?

2023-02-27 16:21 UTC, c-schmitz requested changes

2023-02-27 16:21 UTC, c-schmitz commented on application/helpers/expressions/em_manager_helper.php
> +                        $message = $this->gT('The data could not be saved because the database doesn\'t match the survey structure.');
Please change the message to:
```"Due to a technical problem, your response could not be saved. Please contact the survey administrator <Survey administrator name> <Survey administrator email address> about this problem. You will not be able to proceed with this survey."```

I also think that at this point the survey session should be killed.

2023-02-27 16:43 UTC, gabrieljenik commented on application/helpers/expressions/em_manager_helper.php
> +                        $message = $this->gT('The data could not be saved because the database doesn\'t match the survey structure.');
> Unsure it this point, no ? We already have some other error (for example id of response deleted during survey)

We are kind of using the same mechanism used couple of lines below.
https://github.com/LimeSurvey/LimeSurvey/pull/2946/files#diff-fa8d35264aa59c85d37ca2d1756472996499f06fb346865594378102f5f7abc0L5165

2023-02-27 16:44 UTC, gabrieljenik commented
> `sprintf($this->gT('The data could not be saved dur to %s'),$ex->getMessage())` maybe ?

We didn't want to show technical info to the participant.
So we send one message to the admin and show a different one on the front end.

2023-02-27 22:13 UTC, c-schmitz approved these changes

2023-02-27 22:18 UTC, merged

2023-02-28 21:22 UTC, c-schmitz commented
@gabrieljenik Had to revert this. This would break response export if a token table exists.

2023-02-28 21:48 UTC, gabrieljenik commented
Sorry about this. I will make the nwe method to have a different name, so we can control from where it is being used.