Fixed issue #18655: Data loss if field in response table it missing
LimeSurvey/LimeSurvey pull request #2956
Opened 2023-03-01 19:59 UTC by gabrieljenik

New method: setAllAttributes.

2023-03-02 08:03 UTC, Shnoulle commented
this mean setAttributes have more attribute than setAllAttributes ?

Maybe name is not good ? Or fix can be different ?

The previous issue was about setAttributes with token attributes inside ?  setTableAttributes for the new name ?

2023-03-02 13:08 UTC, gabrieljenik commented
> this mean setAttributes have more attribute than setAllAttributes ?

setAllAttributes is a brand new method.
We can name it differently if prefer.

> The previous issue was about setAttributes with token attributes inside ? setTableAttributes for the new name ?

I prefer to fix that on another ticket. The original issue is a blocking one that needs to be solved.

2023-03-02 13:41 UTC, Shnoulle approved these changes
Unsure on the name , but don't found better idea :)

:+1:

2023-03-06 10:09 UTC, olleharstedt requested changes

2023-03-06 10:09 UTC, olleharstedt commented on application/models/Response.php
> +     * @inhe
inhe? :)

2023-03-23 10:31 UTC, olleharstedt commented
> @olleharstedt Does this requires changes still?

No idea, ping Carsten on Cliq?

2023-03-23 13:18 UTC, gabrieljenik commented
> > @olleharstedt Does this requires changes still?
> 
> No idea, ping Carsten on Cliq?

Ohh, I mention it as you were the one requesting changes.
I will ping Carsten still. Thanks!

2023-03-24 08:22 UTC, merged