Fixed issue #17560: Layout issue when setting user rights.
LimeSurvey/LimeSurvey pull request #3074
Opened 2023-04-25 14:01 UTC by gabrieljenik

Scroll added to table using Bootstrap 3 classes.

2023-04-27 05:40 UTC, Shnoulle requested changes
1. Error on i
2. Solution is worst the bu in UX

2023-04-27 05:40 UTC, Shnoulle commented on application/views/userManagement/partial/editpermissions.php
> +            <table id='UserManagement--userpermissions-table table' class='activecell table table-striped'>
it's id : remove ` table`

it's already in class

2023-04-27 05:40 UTC, Shnoulle commented on application/views/userManagement/partial/editpermissions.php
> +<div class="modal-body selector--edit-permissions-container table-responsive">
table-responsice are awfull for long size tabme, make table unusuable. I send a video on small screen

2023-05-02 20:30 UTC, gabrieljenik commented
Added a full screen modal class

2023-05-03 07:40 UTC, Shnoulle commented
> Added a full screen modal class

on a binary file :sob:

2023-05-03 07:44 UTC, Shnoulle approved these changes

2023-05-03 07:48 UTC, Shnoulle commented
1. Why not in adminbasic with a specific class name dialog-fullwidth for example
2. `width: auto; margin-left: 1em;margin-right: 1em;` seems great too
3. Seems important not needed (and it's better to don't have it) : adminbasic came after bootsrap.

![Capture d’écran du 2023-05-03 09-48-27](https://user-images.githubusercontent.com/1439428/235859106-ad91b955-ed53-4888-8c5b-52f59aeb8798.png)

2023-05-05 06:22 UTC, Shnoulle approved these changes
Thanks ! 😍

2023-05-09 12:47 UTC, merged