Fixed issue #18693: Using checkbox question for yes/no loses data when data entry view
LimeSurvey/LimeSurvey pull request #3109
Opened 2023-05-04 21:12 UTC by gabrieljenik

2023-05-05 06:24 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                // First column (Question)
:+1: we really need more information !

2023-05-05 06:38 UTC, Shnoulle approved these changes
Really great work ! And lot of work.

Just some details and confirmation

2023-05-05 06:38 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                $aDataentryoutput .= "<td>";
Maybe add a class here ? `question` or `question-cell` ?

2023-05-05 06:38 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                $aDataentryoutput .= "<td>\n";
Maybe add a class here ? `answers` or `answers-wrapper`  or `answers-cell` ?

2023-05-05 06:38 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                if (!empty($questionInputs)) {
This was added for short-text and single choice question here ? (i must test quickly)

2023-05-05 06:38 UTC, Shnoulle commented on assets/packages/adminbasics/scss/000-lime-admin-common.scss
> +    .checkbox {
`unseen-item` or `unseen-checkbox` ?

2023-05-05 06:38 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                        $aDataentryoutput .= "<div class=\"checkbox unseen-item\">"
`unseen-checkbox` for class ?

2023-05-05 07:18 UTC, Shnoulle commented
I think it's best if unseen is after answers here.

Maybe 3 columns ? (with some cell with colspan)

2023-05-05 07:22 UTC, Shnoulle commented
For need update by author

1. To confirm : debug=2 throw error
2. Single choice with comment don't seems to get the good unseen state

To test : import https://github.com/LimeSurvey/LimeSurvey/blob/3.x-LTS/docs/demosurveys/ls3_sample_survey_multilingual_fr_de_en_it.lss
activate, launch , move next : response is created with ALL unseen value

![Capture d’écran du 2023-05-05 09-21-56](https://user-images.githubusercontent.com/1439428/236398760-a29eddd2-cf53-4635-bed7-b568f2c4e0f7.png)

2023-05-05 14:33 UTC, Shnoulle commented
Another update to do : for numeric and date : NULL value is set for empty, 
Then 2 solution (without updating DB)

1. Show _Unseen or not answered_
2. Don't show checkbox

To test : same survey, goes at end and submit

![Capture d’écran du 2023-05-05 16-31-19](https://user-images.githubusercontent.com/1439428/236487748-4c409a2c-a0a7-4119-b185-e86dc9c1ed58.png)
![Capture d’écran du 2023-05-05 16-31-37](https://user-images.githubusercontent.com/1439428/236487754-4e439ef6-26a0-4da6-a761-63b708e2cbd0.png)

2023-05-17 21:09 UTC, gabrieljenik commented
@Shnoulle Ready for your reviewal.

Added validation: Unseen can onlybe checked if answer is empty.
Had to add some options for making answers empty on some control types (this screen was rather outdated)
Had to add a hook mechanism on the save.js, as to run custom validation before submitting a form.
(was on 3.x, not on v5, nor v6)

2023-05-18 14:49 UTC, Shnoulle commented
Still the issue with numeric + multi-numeric + + date

2023-05-18 15:21 UTC, Shnoulle requested changes
Still the issue with numeric + multi-numeric + + date

2023-05-18 15:21 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
>                      case Question::QT_K_MULTIPLE_NUMERICAL:
No unsees state for QT_K_MULTIPLE_NUMERICAL

2023-05-18 15:21 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
>                      case Question::QT_D_DATE: //DATE
No unseen state for QT_D_DATE

2023-05-18 15:21 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
>                      case Question::QT_N_NUMERICAL: //NUMERICAL TEXT
No unseen state for QT_N_NUMERICAL

2023-05-19 11:10 UTC, Shnoulle approved these changes
All done !

Except conflict :(

2023-05-25 12:22 UTC, Shnoulle requested changes
No 400 erro if JS broken : savec value and send flash messages

2023-05-26 05:59 UTC, Shnoulle approved these changes

2023-06-13 12:40 UTC, merged