optimized response page
LimeSurvey/LimeSurvey pull request #3149
Opened 2023-05-18 07:47 UTC by jack-han-115

Fixed issue #<Mantis issue number>:
New feature #<Mantis issue number>:
Dev:

2023-05-24 09:08 UTC, twilligls requested changes

2023-05-24 09:08 UTC, twilligls commented on assets/scripts/admin/tokens.js
> -                window.LS.ajaxAlerts(result.success, 'success');
Why did you remove that? I cannot see a replacement success alert somewhere.

2023-05-24 09:11 UTC, twilligls commented
At least one test regarding your changes is failing now

2023-05-25 07:53 UTC, twilligls commented on application/views/responses/browseindex_view.php
> -    <?php if (isset($with_token)) : ?>
I mean in line 9

2023-05-25 07:53 UTC, twilligls commented on application/views/responses/browseindex_view.php
> -                            <td><?php echo $tokeninfo['sent']; ?></td>
I mean in line 8

2023-05-30 12:40 UTC, tiborpacalat requested changes

2023-05-30 12:40 UTC, tiborpacalat commented on application/views/responses/browseindex_view.php
> +                'num_total_answers' => $num_total_answers,
Here is an error probably due to copy paste - you are missing incomplete responses.

2023-05-31 13:04 UTC, merged