Fixed issue #18995: Confidentiality issue about username
LimeSurvey/LimeSurvey pull request #3447
Opened 2023-09-14 18:08 UTC by gabrieljenik

2023-09-15 06:44 UTC, Shnoulle commented on application/models/User.php
> +    public function withListRight($userid = null)
Oh ?

2023-09-15 06:44 UTC, Shnoulle approved these changes

2023-09-15 08:27 UTC, Shnoulle requested changes
Need to be in model too : https://github.com/LimeSurvey/LimeSurvey/blob/5c4fb4e0137d8e564c14d30c3c9563ffd7ecaacd/application/helpers/remotecontrol/remotecontrol_handle.php#L409C31-L409C31

2023-09-15 09:33 UTC, tiborpacalat commented
And some checks are failing. Please make it green :)

2023-09-15 14:44 UTC, gabrieljenik commented
> Need to be in model too : https://github.com/LimeSurvey/LimeSurvey/blob/5c4fb4e0137d8e564c14d30c3c9563ffd7ecaacd/application/helpers/remotecontrol/remotecontrol_handle.php#L409C31-L409C31

What do you mean in model? Check ownership permission in model?
I think usually those checks are outside of the model, right?
I would just add the check on the RC if that's what you mean

2023-09-18 07:53 UTC, Shnoulle commented
> > Need to be in model too : https://github.com/LimeSurvey/LimeSurvey/blob/5c4fb4e0137d8e564c14d30c3c9563ffd7ecaacd/application/helpers/remotecontrol/remotecontrol_handle.php#L409C31-L409C31
> 
> What do you mean in model? Check ownership permission in model? I think usually those checks are outside of the model, right? I would just add the check on the RC if that's what you mean

It's a question, not an affirmation. ping @olleharstedt 

In model : it fix for all controller.

Else here : must be reported for RC too.

2023-09-26 14:00 UTC, Shnoulle approved these changes

2023-09-26 14:11 UTC, merged