New feature #19191: Add destination survey id argument to copy_survey…
LimeSurvey/LimeSurvey pull request #3572
Opened 2023-10-25 00:19 UTC by mfavetti

… rpc function

New feature #19191: Add destination survey id argument to copy_survey rpc function

2023-10-25 07:46 UTC, Shnoulle approved these changes

2023-10-25 07:46 UTC, Shnoulle commented on application/helpers/remotecontrol/remotecontrol_handle.php
>       * @param string $sNewname name of the new survey
phpdoc

2023-10-25 07:46 UTC, Shnoulle requested changes
phpdoc needed

2023-10-25 07:49 UTC, mfavetti commented on application/helpers/remotecontrol/remotecontrol_handle.php
>       * @param string $sNewname name of the new survey
yes, thank you! i added it

2023-10-25 07:49 UTC, mfavetti commented
> phpdoc needed

added

2023-10-25 08:15 UTC, Shnoulle approved these changes

2023-10-25 08:16 UTC, Shnoulle commented
@olleharstedt new feature : need unit test ?

2023-10-26 07:24 UTC, olleharstedt commented
Else just wait for @tiborpacalat to test it. Whatever comes first. :))

2023-10-26 12:54 UTC, merged