Fixed issue #18473: Survey listing : multiple call of template
LimeSurvey/LimeSurvey pull request #3738
Opened 2024-02-14 17:02 UTC by Shnoulle

Dev: avoid multiple call of TemplateConfiguration::model()->search()

2024-02-15 07:00 UTC, Shnoulle commented
Clearly need a better solution here : 

1. no need to call _search_ to have only the list of templet
2. need only the template name from DB

2024-02-15 10:48 UTC, Shnoulle commented
Ok, better fix now !

2024-02-16 09:44 UTC, lajosarpad requested changes
Overall this looks good, we have a duplicated variable initialization though and we will need to get rid of that

2024-02-16 09:44 UTC, lajosarpad commented on application/models/Template.php
> +        $aTemplateList = [];
Why do you create this array twice?

2024-02-16 09:45 UTC, Shnoulle commented on application/models/Template.php
> +        $aTemplateList = [];
Error :)

2024-02-23 18:00 UTC, lajosarpad approved these changes

2024-02-26 08:39 UTC, c-schmitz approved these changes

2024-03-05 16:21 UTC, merged