Fixed issue #19442: Generated analytics script does not properly escape question group name
LimeSurvey/LimeSurvey pull request #3761
Opened 2024-02-27 08:09 UTC by mfavetti

Fixed issue #19442: Generated analytics script does not properly escape question group name

https://bugs.limesurvey.org/view.php?id=19442

master

2024-02-27 09:01 UTC, Shnoulle commented on application/core/LS_Twig_Extension.php
> +        $trackURL = htmlspecialchars($surveyName . '-[' . $surveyId . ']/[' . $page . ']-' . $groupName, ENT_QUOTES);
> this issue is not related to GA itself at all

OK 

> limesurvey is generating javascript (in this context a string), so the contents of the string must be properly escaped or the browser will not be able to properly parse the javascript. i think it's appropriate to escape the function's entire return value as it's dumped directly into a javascript context later by twig:

Then escape it in twig part ?  No ?

> usage of Chtml::encode vs htmlspecialchars seems to be split 50/50 across code base, is Chtml::encode the preferred method?

I don't know, but i always think it's better to use framework functionnality if we have a framework. Personnal opinion here.

2024-02-27 10:03 UTC, mfavetti commented on application/core/LS_Twig_Extension.php
> +        $trackURL = htmlspecialchars($surveyName . '-[' . $surveyId . ']/[' . $page . ']-' . $groupName, ENT_QUOTES);
ok will escape in twig and update tmrw

2024-02-27 10:09 UTC, Shnoulle commented on application/core/LS_Twig_Extension.php
> +        $trackURL = htmlspecialchars($surveyName . '-[' . $surveyId . ']/[' . $page . ']-' . $groupName, ENT_QUOTES);
> ok will escape in twig and update tmrw

Still my opinion :) Not sure at 100% (i set it as comment, not are "To update")

2024-02-27 10:11 UTC, Shnoulle commented on application/core/LS_Twig_Extension.php
> +        $trackURL = htmlspecialchars($surveyName . '-[' . $surveyId . ']/[' . $page . ']-' . $groupName, ENT_QUOTES);
> ok will escape in twig and update tmrw

Oh ! It's not only an opinion : if someone fix it in template : you broke the fix.

This NEED to be done in template only ! Else : broke API.

2024-02-27 10:12 UTC, Shnoulle requested changes
Don't broke API : if someone fix views/subviews/header/google_analytics.twig in extended theme : updating value sent : you broke the theme.

2024-02-28 00:44 UTC, Shnoulle approved these changes

2024-03-04 15:02 UTC, merged