Dev: #19452: Improve usage of getQuestionAttributes DataEntry
LimeSurvey/LimeSurvey pull request #3784
Opened 2024-03-06 17:41 UTC by Shnoulle

2024-03-07 19:01 UTC, lajosarpad requested changes

2024-03-08 07:29 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                    $qidattributes = QuestionAttribute::model()->getQuestionAttributes($arQuestion);
> This looks good 👍

Yep, tested. And we call it after multiple times …

2024-03-11 10:38 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                    $qidattributes = QuestionAttribute::model()->getQuestionAttributes(Question::model()->findByPk($fname['qid']));
Updated : usage on question object in one another question.

2024-03-19 12:12 UTC, Shnoulle commented on application/controllers/admin/DataEntry.php
> +                            if (($oQuestion->other ?? "N") == "Y") {
Really ?

2024-03-19 15:00 UTC, lajosarpad approved these changes

2024-03-21 13:24 UTC, kevin-foster-uk approved these changes

2024-03-21 13:24 UTC, merged