Fixed issue #19397: Editing menu entries not possible
LimeSurvey/LimeSurvey pull request #3862
Opened 2024-05-30 13:36 UTC by Shnoulle

Dev: fix tab to space in view
Dev: parent are not tr, in body
Dev: add data-menuentryid on HTML
Dev: Fix delete on same way

2024-05-31 13:59 UTC, tiborpacalat requested changes

2024-05-31 13:59 UTC, tiborpacalat commented on application/controllers/admin/SurveymenuEntryController.php
> +                throw new CHttpException(404, gT("This menuentries don't exist."));
"menuentries" should be "menu entries"

2024-05-31 13:59 UTC, tiborpacalat commented on application/controllers/admin/SurveymenuEntryController.php
> +            throw new CHttpException(404, gT("Invalid menu entrie."));
"entrie" should be "entry".

2024-05-31 15:31 UTC, Shnoulle commented on application/controllers/admin/SurveymenuEntryController.php
> +                throw new CHttpException(404, gT("This menuentries don't exist."));
"menu entry" single :)

2024-05-31 15:33 UTC, Shnoulle commented on application/controllers/admin/SurveymenuEntryController.php
> +            throw new CHttpException(404, gT("Invalid menu entrie."));
_Invalid menu entry_. for both

2024-05-31 21:34 UTC, gabrieljenik approved these changes
Code structure looks ok

2024-06-03 16:24 UTC, gabrieljenik approved these changes
Code structure looks OK

2024-06-04 11:23 UTC, merged