CT-855: breadcrumb overflow
LimeSurvey/LimeSurvey pull request #3883
Opened 2024-06-13 16:39 UTC by lajosarpad

We removed the third part of the breadcrumbs in the survey editor, as it was duplicated anyway and we overflow the survey name if it happens to be too long

![image](https://github.com/LimeSurvey/LimeSurvey/assets/2805488/97a78bc1-ef3c-4275-b64b-ed5daa6e8857)

![image](https://github.com/LimeSurvey/LimeSurvey/assets/2805488/ab573428-5bfd-4054-858d-2c7f3f932f74)

2024-06-13 16:42 UTC, Shnoulle commented
Then  we REALLY need a REAL title on each page !
https://github.com/LimeSurvey/LimeSurvey/pull/3825

2024-06-13 21:23 UTC, c-schmitz commented
I think overflowing is a terrible idea. There are surveys with really long survey titles, which will create a mess for sure.

2024-06-14 06:16 UTC, Shnoulle commented
The breadcrumb need to get all width, not only the left menu part.

2024-06-14 10:50 UTC, ptelu commented
here are 2 quick examples on the left, of what could be done
1 and 2 are quick examples form me
PR is on the right and the current version of this PR
im using the max length allowed by survey title
the Surveys links seems redundant as we already have a link to the survey on the top navigation
![image](https://github.com/LimeSurvey/LimeSurvey/assets/22096081/c33e40d6-ab2a-4eb5-ac8a-c7316fbe1627)

2024-06-14 11:21 UTC, lajosarpad commented
@jorynag3l Do we need a link to the surveys in the breadcrumb, or is it better to show only the title of the survey, as @ptelu suggested?

Which approach looks the best according to you from ptelu's screenshot?

2024-07-05 06:18 UTC, Shnoulle commented
> @jorynag3l Do we need a link to the surveys in the breadcrumb, or is it better to show only the title of the survey, as @ptelu suggested?
> 
> Which approach looks the best according to you from ptelu's screenshot?


Then it's not a breadcrumb : breadcrumb are a navigation help …

2024-07-05 19:13 UTC, jorynag3l commented
Some people may be used to clicking on the Surveys / link. Therefore we kept it for now.
We will commit this version. Any further adjustments can be debated in another PR.

2024-07-06 08:25 UTC, Shnoulle commented
> Some users might be used to clicking on the Surveys / link. Therefore we kept it for now. We will commit this version. Any further adjustments can be debated in another PR.

I don't say it's needed or not, it's just NOT a breadcrumb if there are no link. It's a title.

1. A [breadcrumb](https://developer.mozilla.org/en-US/docs/Glossary/Breadcrumb), it's a navigation helper
2. A title/[header](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header) give information on current page/section : then need : Survey name + current action + current Group + current question etc …

here it's more a header, then lack of a lot of information.

2024-07-06 09:13 UTC, Shnoulle commented
If we add only survey name here : telle me the pro of this PR against this one : https://github.com/LimeSurvey/LimeSurvey/pull/3825#issuecomment-2173488103


**Pro** 
Here : 

1. Have the name of the survey

[Other](https://github.com/LimeSurvey/LimeSurvey/pull/3825#issuecomment-2173488103) : 

1. Have the name of the survey
2. Have the information on current action/question/group
3. Have the breadcrumb

**Con**

Here

1. Breadcrumb disappear : one link less to go to group (for example)
2. No information on current group

Other

2024-07-06 09:28 UTC, jorynag3l commented
Hey Deni,
Let's commit to this version and debated further adjustments if needed in another PR.

2024-07-06 13:28 UTC, Shnoulle commented
The other PR is here since April. https://github.com/LimeSurvey/LimeSurvey/pull/3825

2024-07-08 09:33 UTC, c-schmitz commented
Current status:
![image](https://github.com/LimeSurvey/LimeSurvey/assets/1364282/0b69cde0-8343-47a4-a1b3-4ca5bb6142b3)

2024-07-08 09:35 UTC, c-schmitz commented
Current status: 
![image](https://github.com/LimeSurvey/LimeSurvey/assets/1364282/8d630e75-6bb9-4321-8803-fab22d2bb8fb)

2024-07-08 09:47 UTC, c-schmitz commented
In total I see this PR only as a very minor improvement on the original problem.

2024-07-08 09:49 UTC, c-schmitz requested changes

2024-07-08 09:49 UTC, c-schmitz commented on application/extensions/BreadcrumbWidget/BreadcrumbWidget.php
> +                'text' => $survey->defaultlanguage->surveyls_title . "({$survey->sid})"
Space is missing before the ID

2024-07-08 09:55 UTC, merged

2024-07-08 10:12 UTC, c-schmitz commented
OK, after further review I reverted the PR. It is not an improvement.