LA-136: Undeletable default menu entries
LimeSurvey/LimeSurvey pull request #3996
Opened 2024-10-18 09:53 UTC by mohabmes

2024-10-24 12:50 UTC, c-schmitz requested changes
Update shoul

2024-10-24 12:50 UTC, c-schmitz commented on application/helpers/update/updates/Update_625.php
> +                $this->db->createCommand()->insert('{{surveymenu_entries}}', $aSurveymenuentry);
Updates should never use models, because models can change over time.

2024-11-06 15:10 UTC, twilligls requested changes

2024-11-07 10:07 UTC, twilligls approved these changes

2024-11-07 10:08 UTC, twilligls approved these changes

2024-11-07 10:17 UTC, merged